name: "CodeQL Analysis"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: cpp  # Ensure it's scanning C/C++ code

    - name: Build project
      run: |
        sudo apt update && sudo apt install -y build-essential
        make || gcc -o vuln vuln.c

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/security-extended"
